apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: scd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6              # or ahmadm2704/mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: IMS
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: scd
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
