name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Trigger the action when code is pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Using an Ubuntu runner for CI

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the code from the repository

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # Set up Docker Buildx for multi-platform builds

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # GitHub secret for Docker Hub username
        password: ${{ secrets.DOCKER_PASSWORD }}  # GitHub secret for Docker Hub password or PAT

    - name: Build Frontend Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-frontend-app:latest ./Frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/my-frontend-app:latest  # Push the image to Docker Hub

    - name: Build Backend Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-backend-app:latest ./Backend
        docker push ${{ secrets.DOCKER_USERNAME }}/my-backend-app:latest  # Push the image to Docker Hub

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1  # Set up kubectl to interact with Kubernetes
      with:
        version: 'v1.21.2'  # Use the Kubernetes version that you need

    - name: Configure kubectl to use Minikube
      run: |
        minikube start
        kubectl config use-context minikube  # Set kubectl to use the Minikube cluster

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/  # Apply the Kubernetes manifests for deployment

